# Generated by Django 6.0.3 on 2026-03-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="task_files/"),
        ),
    ]
