# Generated by Django 6.0.3 on 2026-03-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_task_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
