# Generated by Django 6.0.3 on 2026-03-21 10:45

from django.db import migrations, models


def populate_status_changed(apps, schema_editor):
    Task = apps.get_model("accounts", "Task")
    TaskUpdate = apps.get_model("accounts", "TaskUpdate")

    for task in Task.objects.all():
        previous_status = None
        updates = TaskUpdate.objects.filter(task=task).order_by("created_at", "id")

        for update in updates:
            if previous_status is None:
                update.status_changed = False
            else:
                update.status_changed = update.status != previous_status

            update.save(update_fields=["status_changed"])
            previous_status = update.status


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_task_timestamps_and_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskupdate",
            name="status_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_status_changed, migrations.RunPython.noop),
    ]
