# Generated by Django 6.0.3 on 2026-03-21 11:20

from django.db import migrations, models


def populate_previous_status(apps, schema_editor):
    Task = apps.get_model("accounts", "Task")
    TaskUpdate = apps.get_model("accounts", "TaskUpdate")

    for task in Task.objects.all():
        last_effective_status = None
        updates = TaskUpdate.objects.filter(task=task).order_by("created_at", "id")

        for update in updates:
            if update.status_changed:
                update.previous_status = last_effective_status
            else:
                update.previous_status = None

            update.save(update_fields=["previous_status"])
            last_effective_status = update.status


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_taskupdate_status_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskupdate",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[("todo", "To Do"), ("in_progress", "In Progress"), ("done", "Done")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.RunPython(populate_previous_status, migrations.RunPython.noop),
    ]
