# Generated by Django 6.0.3 on 2026-03-21 11:55

from django.db import migrations, models


SYSTEM_ASSIGNED_PREFIX = "Task assigned to "
SYSTEM_UNASSIGNED_NOTE = "Task unassigned."


def populate_assignment_snapshots(apps, schema_editor):
    Task = apps.get_model("accounts", "Task")
    TaskUpdate = apps.get_model("accounts", "TaskUpdate")

    for task in Task.objects.all():
        last_known_assignee = None
        updates = TaskUpdate.objects.filter(task=task).order_by("created_at", "id")

        for update in updates:
            update.previous_assignee = None
            update.current_assignee = None

            if update.note.startswith(SYSTEM_ASSIGNED_PREFIX):
                update.previous_assignee = last_known_assignee
                update.current_assignee = update.note.removeprefix(SYSTEM_ASSIGNED_PREFIX).rstrip(".")
                last_known_assignee = update.current_assignee
            elif update.note == SYSTEM_UNASSIGNED_NOTE:
                update.previous_assignee = last_known_assignee
                update.current_assignee = None
                last_known_assignee = None

            update.save(update_fields=["previous_assignee", "current_assignee"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_taskupdate_previous_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskupdate",
            name="current_assignee",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="taskupdate",
            name="previous_assignee",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RunPython(populate_assignment_snapshots, migrations.RunPython.noop),
    ]
