# Generated by Django 6.0.3 on 2026-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_taskupdate_assignment_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskupdate",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="task_update_files/"),
        ),
    ]
