# Generated by Django 6.0.3 on 2026-04-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='acceptance_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='backlog_state',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('selected_for_sprint', 'Selected for Sprint'), ('ready_for_test', 'Ready for Test'), ('done', 'Done')], default='backlog', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='item_type',
            field=models.CharField(choices=[('story', 'Story'), ('bug', 'Bug'), ('task', 'Task')], default='story', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
    ]
