# Generated by Django 6.0.3 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_task_review_feedback_task_review_requested_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="password_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
