apiVersion: v1
kind: Service
metadata:
  name: pdms-service
  labels:
    app: pdms
spec:
  selector:
    app: pdms
  ports:
    - protocol: TCP
      port: 80        # External port exposed by the service
      targetPort: 8000 # Django container port
  type: LoadBalancer   # Exposes service externally (use ClusterIP for internal-only)
  sessionAffinity: None
