apiVersion: v1
kind: Service
metadata:
  name: pdms-service
spec:
  selector:
    app: pdms
  ports:
    - protocol: TCP
      port: 80        # external port
      targetPort: 8000 # Django container port
  type: LoadBalancer
  sessionAffinity: None
